# Site settings
title: Vaibhav Deokar
email: vaibhav.2000.deokar@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Exploring AI, creativity, and technology. Seeking a challenging role to utilize technical and creative skills for organizational growth.
baseurl: "" # the subpath of your site, e.g. /blog. If hosted at root, leave empty.
url: "https://vaibhavdeokar.netlify.app" # the base hostname & protocol for your site
twitter_username: vaibhavdeoka_20
github_username:  dev-ai-kar
linkedin_username: vaibhav-deokar
default_image: /images/hero-bg-1200.jpg # Default image for social media previews

# Build settings
markdown: kramdown
theme: null # Using custom theme based on existing files
plugins:
  - jekyll-feed
  - jekyll-archives # Add any Jekyll plugins inside the list

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE

# Include files/folders that start with _ or . by default
include: [] # Removed _cpp_notes/img-data, as images are now handled by build script

# Keep existing asset folders
keep_files:
  - css
  - js
  - images
  - Vaibhav-Deokar-Resume.pdf # Ensure PDF is copied

# Collections (Optional, for blog posts or other content types)
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title.html
  cpp_notes: # Add the new collection for C++ notes
    output: true # Generate individual pages for each note
    permalink: /notes/cpp/:path.html # URL structure for C++ notes
  algorithm_notes:
    output: true
    permalink: /notes/algorithms/:path.html
  nlp_notes:
    output: true
    permalink: /notes/nlp/:path.html

# Defaults for collections
defaults:
  -
    scope:
      path: ""
      type: "cpp_notes"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "algorithm_notes"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "nlp_notes"
    values:
      layout: "post"

# Jekyll Archives configuration
jekyll-archives:
  enabled:
    - categories
    # - tags # Uncomment if you want tag archives too
  layout: category_archive # Specify the layout file name
  permalinks:
    category: '/categories/:name/'
    # tag: '/tags/:name/' # Uncomment if using tags
